name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      package-file-name: ${{ steps.build-package.outputs.package }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: false
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build Package
        id: build-package
        run: |
          pnpm build
          echo "package=$(pnpm pack)" >> "$GITHUB_OUTPUT"
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: npm-package
          path: ./*.tgz

  publish-to-npm:
    name: "Publish to NPM"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Package
        id: download-package
        uses: actions/download-artifact@v4
        with:
          name: npm-package
      - run: stat ${{ steps.download-package.outputs.download-path }}/${{ needs.build.outputs.package-file-name }}
      - name: NPM Publish
        uses: JS-DevTools/npm-publish@v3.1.1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ${{ steps.download-package.outputs.download-path }}/${{ needs.build.outputs.package-file-name }}
